services:
  krakend_ce:
    image: devopsfaith/krakend:watch
    volumes:
      - ./config:/etc/krakend/config/
      - /plugins:/etc/krakend/plugins/
    ports:
      - "3890:3890"
    command: ["run", "-d", "-c", "/etc/krakend/config/krakend.json"]